travis:
  secure:
    BINSTAR_TOKEN: Gb1TJSo05GsAOAWSex78XosB0qabULnqSpYIjDaZ9smj8nmixdfcjGuJFtIP9UOzPvXIme3dKTAiBP5u/ujAfAcEZjaXxB2dHxuq71qgwzcIZRbkuPpy89TPQXAIejAMO9AfgD1sA2GRDyMM11hnA+FPSM/yJgK/ps+DupUp4UGxcb7sjOWSh3X4gsVi6LMKVXByW8KNauqUBfxYgmfz+RJVkRVFoPnLUEfuIfg2ZLOj9IsmAUqaljDS2jjKTpX3/ys91X+hX/I+PyaIDRs9pwBFk50qnWY4Nc8MsPR6PK8/JBSsKwk697eyqgQ1vNQuyj95XPBiThxOYyLayMY8KjOnNkMAcwqzweXP07pdlJPJ+YZ9XVBqjOzaKTzkUUgUfCnffc41ezLV2ptiqIhV2N9AqYjcXDdN5sk8wFDdTLGCJBGlOHWf7Yz67xhu2rFecNoOCL/kv5v36MCzLMqfP/NQXqyEYsrob6YQQDfK2vUPmqDsDn24cswmllXukJi8X4l21GSYYxBi8gqAkQspeGK/HNIeTf+wdeyF6nx6IqgNVjiIxm7bcIATeflQpQGnme6UTXLd8tsaAXcCIsCyLTCgFQa2CwSS9mTnPEddbJRRI77AFp1G09mwZCb19n6QSwY2RIDZjGR70ZqKsGd37sksPGrCp9Kpz0XFntsnnEk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
